### ISSUE TITLE
Error when starting generator with Jhipster 6.9

### ISSUE THREAD

**Issue by poornerd** [amitjindal/generator-jhipster-postgresuuid-converter#3]
```
generator-jhipster@6.9.0
git version 2.24.3 (Apple Git-128)
node: v14.3.0
npm: 6.14.4
yeoman: 3.1.1
yarn: 1.22.4
```

Here is the error I am getting.  Maybe it is because this is not maintained and doesn't work with the current JHipster?

```
TypeError: Cannot read property 'initializing' of undefined
    at child.queueOwnTask (/usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:799:34)
    at /usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:843:45
    at Array.forEach (<anonymous>)
    at child.queueOwnTasks (/usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:843:18)
    at /usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:12
    at new Promise (<anonymous>)
    at child.runWithOptions (/usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1004:21)
    at child.run (/usr/local/lib/node_modules/generator-jhipster-postgresuuid-converter/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:963:26)
    at /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:798:36
    at new Promise (<anonymous>)
```

**Comment by amitjindal** [comment]
Hi Brian, you are correct. This is not maintained as I have moved on to other things and just kept it here for anyone who needs to see the old code. I will mark this unmaintained.
